theme:
  name: material

site_name: Methods and Tools
site_author: "Sascha Lucius"
site_url: https://saschalucius.github.io/methods-and-tools2/

repo_url: https://github.com/SaschaLucius/methods-and-tools2
